#!/usr/bin/env bash
# Bash script to display information about subdomains

# Function to get DNS information for a subdomain
dns_config () {
    local domain="$1"
    local subdomain="$2"

    # Use dig to get the DNS information for the subdomain
    script=$(dig +short "$subdomain.$domain")

    # Check if the subdomain exists
    if [ -n "$script" ]; then
        # Retrieve the record type and destination IP
        record_type=$(dig +short -t ANY "$subdomain.$domain" | awk 'NR==1 {print $4}')
        destination=$(dig +short "$subdomain.$domain" | awk 'NR==1 {print $1}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "The subdomain $subdomain does not exist for $domain"
    fi
}

# Check the number of arguments
if [ "$#" -eq 1 ]; then
  # If only one argument is provided, check default subdomains
  domains=("www" "lb-01" "web-01" "web-02")
  for sub in "${domains[@]}"; do
      # Call the function for each default subdomain
      dns_config "$1" "$sub"
  done
elif [ "$#" -eq 2 ]; then
  # If two arguments are provided, call the function for the specified subdomain
  dns_config "$1" "$2"
else
  # Display usage information if the number of arguments is incorrect
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi
