#!/usr/bin/env bash
# Script that displays Best school 10 times.
# But at 9th iteration display Best School and then Hi on a new line.
str="Best School"
i=1
while [ "$i" -le 10 ]
do
	echo "$str";
	if [ "$i" -eq 9 ]; then
		echo "Hi";
	fi
	(( i++ ));
done
